### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by adeluccar** [cirosantilli/softcover_vagrant#2] opened 2016-03-10 05:35 UTC
Hey!

Any ideas on why `vagrant up` could be failing?
### Error Output

This is the entire message sequence:

> softcover_vagrant git:(master) vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Checking if box 'cirosantilli/precise64_softcover' is up to date...
> ==> default: Clearing any previously set forwarded ports...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
> ==> default: Forwarding ports...
>     default: 4000 (guest) => 4000 (host) (adapter 1)
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> A customization command failed:
> 
> ["modifyvm", :id, "--cpus", "1", "--memory", "1024", "--name", "cirosantilli/precise64_softcover"]
> 
> The following error was experienced:
> # <Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
> 
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["modifyvm", "efc221d3-1bbf-4b77-b920-4494d5cd6473", "--cpus", "1", "--memory", "1024", "--name", "cirosantilli/precise64_softcover"]
> 
> Stderr: VBoxManage: error: Could not rename the settings file '/Users/alberto/VirtualBox VMs/cirosantilli/precise64_softcover/softcover_vagrant_default_1457587062401_81865.vbox' to '/Users/alberto/VirtualBox VMs/cirosantilli/precise64_softcover/cirosantilli/precise64_softcover.vbox' (VERR_FILE_NOT_FOUND)
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
> VBoxManage: error: Context: "SaveSettings()" at line 3016 of file VBoxManageModifyVM.cpp
> 
> Please fix this customization and try again.
### Info on Host Machine

Host machine: Mac OS X Yosemite 10.10.5 (just from a clean install)

VirtualBox 5.0.16 r105871
`which virtualbox` => `/usr/local/bin/virtualbox`

Vagrant 1.8.1
`which vagrant` => `/usr/local/bin/vagrant` (although it is symlinked from `/opt/vagrant/bin/vagrant`)

Both installed with [Homebrew Cask](https://caskroom.github.io)

**Comment by adeluccar** [comment] 2016-03-10 06:03
Update: Just spun an ubuntu/trusty32 instance to check if my setup could be the culprit.
It went without trouble. So I think something could be wrong with this box.

Any ideas?

**Comment by jhpaul** [comment] 2016-03-10 06:20
since the problem occurs on this line:

```
["modifyvm", :id, "--cpus", "1", "--memory", "1024", "--name", "cirosantilli/precise64_softcover"]
```

I suspect it could be due to the slash in the name. There is [some evidence](https://www.virtualbox.org/ticket/6541) to back that up (this ticket is very old, but it's possible it was fixed on linux and not osx, or is a bug in vagrant).

perhaps try changing [this variable](https://github.com/cirosantilli/softcover_vagrant/blob/master/Vagrantfile#L9) to `box = "precise64_softcover"`

Also, this project hasn't been updated in quite a while, possible there's a conflict with changes in vagrant.

**Comment by cirosantilli** [comment] 2016-03-10 06:32
Hey there,

I'm sorry but I've given up on this project.

I don't know what is the cause of the problem. If you make a pull request, I'm happy :-), and I will quickly look into it and merge, but I don't intend to test PRs / reproduce bugs.

I've found that to me, softcover is not worth it. It is better to enrich lightweight markup languages (e.g. pandoc on Markdown) which are getting tons of traction, than to derich the unfixable LaTeX to get HTML / PDF cross compile.

**Comment by adeluccar** [comment] 2016-03-10 08:11
@jhpaul That did it. Thank you. Still learning Vagrant. Box spun and all Softcover dependencies seem to pass.

**Comment by adeluccar** [comment] 2016-03-10 08:12
@cirosantilli That's interesting. How are you managing the cross references and formula generation with Markdown?

**Comment by cirosantilli** [comment] 2016-03-10 08:33
@adeluccar I don't use those much in my day to day, but I think pandoc does equation references http://tex.stackexchange.com/questions/111868/pandoc-how-can-i-get-numbered-latex-equations-to-show-up-in-both-pdf-and-html-o

What do you mean by formula generation? Math rendering? `$ x^2 $` works on several markdown implementations including pandoc, HTML output via `MathJax` (since browsers other than Firefox and Safari don't feel like implementing Mathml).

Markdown extensions can also refer to headers.

**Closed as completed** 2017-07-11 04:18 UTC
